// Travel-buddy catalog (founder, 2026-10-05): every breed a traveler can pick for a
// virtual pet — species → breed → coat color → name. Pure data, no imports.
// Breeds: dogs/cats alphabetical with "Mixed / rescue" (and Domestic SH/LH for cats)
// pinned first; hamsters/birds/reptiles kept in most-common-first order.
// Coats: curated natural colorways; belly is always lighter than body, ear darker.

export const SPECIES = [
  { key: "dog", name: "Dog", emoji: "🐶" },
  { key: "cat", name: "Cat", emoji: "🐱" },
  { key: "hamster", name: "Hamster", emoji: "🐹" },
  { key: "bird", name: "Bird", emoji: "🦜" },
  { key: "reptile", name: "Iguana & dragons", emoji: "🦎" },
];

export const BREEDS = {
  dog: [
    { key: "mixed", name: "Mixed / rescue" },
    { key: "affenpinscher", name: "Affenpinscher" },
    { key: "afghan-hound", name: "Afghan Hound" },
    { key: "airedale-terrier", name: "Airedale Terrier" },
    { key: "akita", name: "Akita" },
    { key: "alaskan-klee-kai", name: "Alaskan Klee Kai" },
    { key: "alaskan-malamute", name: "Alaskan Malamute" },
    { key: "american-bulldog", name: "American Bulldog" },
    { key: "american-bully", name: "American Bully" },
    { key: "american-cocker-spaniel", name: "American Cocker Spaniel" },
    { key: "american-english-coonhound", name: "American English Coonhound" },
    { key: "american-eskimo-dog", name: "American Eskimo Dog" },
    { key: "american-foxhound", name: "American Foxhound" },
    { key: "american-hairless-terrier", name: "American Hairless Terrier" },
    { key: "american-pit-bull-terrier", name: "American Pit Bull Terrier" },
    { key: "american-staffordshire-terrier", name: "American Staffordshire Terrier" },
    { key: "american-water-spaniel", name: "American Water Spaniel" },
    { key: "anatolian-shepherd-dog", name: "Anatolian Shepherd Dog" },
    { key: "appenzeller-sennenhund", name: "Appenzeller Sennenhund" },
    { key: "australian-cattle-dog", name: "Australian Cattle Dog" },
    { key: "australian-kelpie", name: "Australian Kelpie" },
    { key: "australian-shepherd", name: "Australian Shepherd" },
    { key: "australian-terrier", name: "Australian Terrier" },
    { key: "azawakh", name: "Azawakh" },
    { key: "barbet", name: "Barbet" },
    { key: "basenji", name: "Basenji" },
    { key: "basset-fauve-de-bretagne", name: "Basset Fauve de Bretagne" },
    { key: "basset-hound", name: "Basset Hound" },
    { key: "bavarian-mountain-hound", name: "Bavarian Mountain Hound" },
    { key: "beagle", name: "Beagle" },
    { key: "bearded-collie", name: "Bearded Collie" },
    { key: "beauceron", name: "Beauceron" },
    { key: "bedlington-terrier", name: "Bedlington Terrier" },
    { key: "belgian-laekenois", name: "Belgian Laekenois" },
    { key: "belgian-malinois", name: "Belgian Malinois" },
    { key: "belgian-sheepdog", name: "Belgian Sheepdog (Groenendael)" },
    { key: "belgian-tervuren", name: "Belgian Tervuren" },
    { key: "bergamasco-sheepdog", name: "Bergamasco Sheepdog" },
    { key: "berger-picard", name: "Berger Picard" },
    { key: "bernedoodle", name: "Bernedoodle" },
    { key: "bernese-mountain-dog", name: "Bernese Mountain Dog" },
    { key: "bichon-frise", name: "Bichon Frise" },
    { key: "biewer-terrier", name: "Biewer Terrier" },
    { key: "black-and-tan-coonhound", name: "Black and Tan Coonhound" },
    { key: "black-russian-terrier", name: "Black Russian Terrier" },
    { key: "bloodhound", name: "Bloodhound" },
    { key: "bluetick-coonhound", name: "Bluetick Coonhound" },
    { key: "boerboel", name: "Boerboel" },
    { key: "bolognese", name: "Bolognese" },
    { key: "border-collie", name: "Border Collie" },
    { key: "border-terrier", name: "Border Terrier" },
    { key: "borzoi", name: "Borzoi" },
    { key: "boston-terrier", name: "Boston Terrier" },
    { key: "bouvier-des-flandres", name: "Bouvier des Flandres" },
    { key: "boxer", name: "Boxer" },
    { key: "boykin-spaniel", name: "Boykin Spaniel" },
    { key: "bracco-italiano", name: "Bracco Italiano" },
    { key: "briard", name: "Briard" },
    { key: "brittany", name: "Brittany" },
    { key: "broholmer", name: "Broholmer" },
    { key: "brussels-griffon", name: "Brussels Griffon" },
    { key: "bull-terrier", name: "Bull Terrier" },
    { key: "bulldog", name: "Bulldog (English)" },
    { key: "bullmastiff", name: "Bullmastiff" },
    { key: "cairn-terrier", name: "Cairn Terrier" },
    { key: "canaan-dog", name: "Canaan Dog" },
    { key: "cane-corso", name: "Cane Corso" },
    { key: "cardigan-welsh-corgi", name: "Cardigan Welsh Corgi" },
    { key: "carolina-dog", name: "Carolina Dog" },
    { key: "catahoula-leopard-dog", name: "Catahoula Leopard Dog" },
    { key: "caucasian-shepherd-dog", name: "Caucasian Shepherd Dog" },
    { key: "cavachon", name: "Cavachon" },
    { key: "cavalier-king-charles-spaniel", name: "Cavalier King Charles Spaniel" },
    { key: "cavapoo", name: "Cavapoo" },
    { key: "central-asian-shepherd-dog", name: "Central Asian Shepherd Dog" },
    { key: "cesky-terrier", name: "Cesky Terrier" },
    { key: "chesapeake-bay-retriever", name: "Chesapeake Bay Retriever" },
    { key: "chihuahua", name: "Chihuahua" },
    { key: "chinese-crested", name: "Chinese Crested" },
    { key: "chinese-shar-pei", name: "Chinese Shar-Pei" },
    { key: "chinook", name: "Chinook" },
    { key: "chow-chow", name: "Chow Chow" },
    { key: "cirneco-dell-etna", name: "Cirneco dell'Etna" },
    { key: "clumber-spaniel", name: "Clumber Spaniel" },
    { key: "cockapoo", name: "Cockapoo" },
    { key: "collie-rough", name: "Collie (Rough)" },
    { key: "collie-smooth", name: "Collie (Smooth)" },
    { key: "coton-de-tulear", name: "Coton de Tulear" },
    { key: "croatian-sheepdog", name: "Croatian Sheepdog" },
    { key: "curly-coated-retriever", name: "Curly-Coated Retriever" },
    { key: "czechoslovakian-vlcak", name: "Czechoslovakian Vlcak" },
    { key: "dachshund", name: "Dachshund" },
    { key: "dalmatian", name: "Dalmatian" },
    { key: "dandie-dinmont-terrier", name: "Dandie Dinmont Terrier" },
    { key: "danish-swedish-farmdog", name: "Danish-Swedish Farmdog" },
    { key: "doberman-pinscher", name: "Doberman Pinscher" },
    { key: "dogo-argentino", name: "Dogo Argentino" },
    { key: "dogue-de-bordeaux", name: "Dogue de Bordeaux" },
    { key: "drentsche-patrijshond", name: "Drentsche Patrijshond" },
    { key: "drever", name: "Drever" },
    { key: "dutch-shepherd", name: "Dutch Shepherd" },
    { key: "english-cocker-spaniel", name: "English Cocker Spaniel" },
    { key: "english-foxhound", name: "English Foxhound" },
    { key: "english-setter", name: "English Setter" },
    { key: "english-springer-spaniel", name: "English Springer Spaniel" },
    { key: "english-toy-spaniel", name: "English Toy Spaniel" },
    { key: "entlebucher-mountain-dog", name: "Entlebucher Mountain Dog" },
    { key: "estrela-mountain-dog", name: "Estrela Mountain Dog" },
    { key: "eurasier", name: "Eurasier" },
    { key: "field-spaniel", name: "Field Spaniel" },
    { key: "fila-brasileiro", name: "Fila Brasileiro" },
    { key: "finnish-lapphund", name: "Finnish Lapphund" },
    { key: "finnish-spitz", name: "Finnish Spitz" },
    { key: "flat-coated-retriever", name: "Flat-Coated Retriever" },
    { key: "french-bulldog", name: "French Bulldog" },
    { key: "german-longhaired-pointer", name: "German Longhaired Pointer" },
    { key: "german-pinscher", name: "German Pinscher" },
    { key: "german-shepherd-dog", name: "German Shepherd Dog" },
    { key: "german-shorthaired-pointer", name: "German Shorthaired Pointer" },
    { key: "german-spitz", name: "German Spitz" },
    { key: "german-wirehaired-pointer", name: "German Wirehaired Pointer" },
    { key: "giant-schnauzer", name: "Giant Schnauzer" },
    { key: "glen-of-imaal-terrier", name: "Glen of Imaal Terrier" },
    { key: "golden-retriever", name: "Golden Retriever" },
    { key: "goldendoodle", name: "Goldendoodle" },
    { key: "gordon-setter", name: "Gordon Setter" },
    { key: "grand-basset-griffon-vendeen", name: "Grand Basset Griffon Vendeen" },
    { key: "great-dane", name: "Great Dane" },
    { key: "great-pyrenees", name: "Great Pyrenees" },
    { key: "greater-swiss-mountain-dog", name: "Greater Swiss Mountain Dog" },
    { key: "greenland-dog", name: "Greenland Dog" },
    { key: "greyhound", name: "Greyhound" },
    { key: "hamiltonstovare", name: "Hamiltonstovare" },
    { key: "hanoverian-scenthound", name: "Hanoverian Scenthound" },
    { key: "harrier", name: "Harrier" },
    { key: "havanese", name: "Havanese" },
    { key: "hokkaido", name: "Hokkaido" },
    { key: "hovawart", name: "Hovawart" },
    { key: "ibizan-hound", name: "Ibizan Hound" },
    { key: "icelandic-sheepdog", name: "Icelandic Sheepdog" },
    { key: "irish-red-and-white-setter", name: "Irish Red and White Setter" },
    { key: "irish-setter", name: "Irish Setter" },
    { key: "irish-terrier", name: "Irish Terrier" },
    { key: "irish-water-spaniel", name: "Irish Water Spaniel" },
    { key: "irish-wolfhound", name: "Irish Wolfhound" },
    { key: "italian-greyhound", name: "Italian Greyhound" },
    { key: "jack-russell-terrier", name: "Jack Russell Terrier" },
    { key: "jagdterrier", name: "Jagdterrier" },
    { key: "japanese-chin", name: "Japanese Chin" },
    { key: "japanese-spitz", name: "Japanese Spitz" },
    { key: "kai-ken", name: "Kai Ken" },
    { key: "kangal-shepherd-dog", name: "Kangal Shepherd Dog" },
    { key: "karelian-bear-dog", name: "Karelian Bear Dog" },
    { key: "keeshond", name: "Keeshond" },
    { key: "kerry-blue-terrier", name: "Kerry Blue Terrier" },
    { key: "kishu-ken", name: "Kishu Ken" },
    { key: "komondor", name: "Komondor" },
    { key: "kooikerhondje", name: "Kooikerhondje" },
    { key: "korean-jindo", name: "Korean Jindo" },
    { key: "kuvasz", name: "Kuvasz" },
    { key: "labradoodle", name: "Labradoodle" },
    { key: "labrador-retriever", name: "Labrador Retriever" },
    { key: "lagotto-romagnolo", name: "Lagotto Romagnolo" },
    { key: "lakeland-terrier", name: "Lakeland Terrier" },
    { key: "lancashire-heeler", name: "Lancashire Heeler" },
    { key: "lapponian-herder", name: "Lapponian Herder" },
    { key: "leonberger", name: "Leonberger" },
    { key: "lhasa-apso", name: "Lhasa Apso" },
    { key: "lowchen", name: "Lowchen" },
    { key: "maltese", name: "Maltese" },
    { key: "maltipoo", name: "Maltipoo" },
    { key: "manchester-terrier", name: "Manchester Terrier" },
    { key: "maremma-sheepdog", name: "Maremma Sheepdog" },
    { key: "mastiff", name: "Mastiff (English)" },
    { key: "miniature-american-shepherd", name: "Miniature American Shepherd" },
    { key: "miniature-bull-terrier", name: "Miniature Bull Terrier" },
    { key: "miniature-pinscher", name: "Miniature Pinscher" },
    { key: "miniature-schnauzer", name: "Miniature Schnauzer" },
    { key: "mountain-cur", name: "Mountain Cur" },
    { key: "mudi", name: "Mudi" },
    { key: "neapolitan-mastiff", name: "Neapolitan Mastiff" },
    { key: "newfoundland", name: "Newfoundland" },
    { key: "norfolk-terrier", name: "Norfolk Terrier" },
    { key: "norrbottenspets", name: "Norrbottenspets" },
    { key: "norwegian-buhund", name: "Norwegian Buhund" },
    { key: "norwegian-elkhound", name: "Norwegian Elkhound" },
    { key: "norwegian-lundehund", name: "Norwegian Lundehund" },
    { key: "norwich-terrier", name: "Norwich Terrier" },
    { key: "nova-scotia-duck-tolling-retriever", name: "Nova Scotia Duck Tolling Retriever" },
    { key: "old-english-sheepdog", name: "Old English Sheepdog" },
    { key: "otterhound", name: "Otterhound" },
    { key: "papillon", name: "Papillon" },
    { key: "parson-russell-terrier", name: "Parson Russell Terrier" },
    { key: "patterdale-terrier", name: "Patterdale Terrier" },
    { key: "pekingese", name: "Pekingese" },
    { key: "pembroke-welsh-corgi", name: "Pembroke Welsh Corgi" },
    { key: "perro-de-presa-canario", name: "Perro de Presa Canario" },
    { key: "peruvian-inca-orchid", name: "Peruvian Inca Orchid" },
    { key: "petit-basset-griffon-vendeen", name: "Petit Basset Griffon Vendeen" },
    { key: "pharaoh-hound", name: "Pharaoh Hound" },
    { key: "plott-hound", name: "Plott Hound" },
    { key: "pointer", name: "Pointer" },
    { key: "polish-lowland-sheepdog", name: "Polish Lowland Sheepdog" },
    { key: "pomeranian", name: "Pomeranian" },
    { key: "pomsky", name: "Pomsky" },
    { key: "poodle-miniature", name: "Poodle (Miniature)" },
    { key: "poodle-standard", name: "Poodle (Standard)" },
    { key: "poodle-toy", name: "Poodle (Toy)" },
    { key: "porcelaine", name: "Porcelaine" },
    { key: "portuguese-podengo", name: "Portuguese Podengo" },
    { key: "portuguese-water-dog", name: "Portuguese Water Dog" },
    { key: "pudelpointer", name: "Pudelpointer" },
    { key: "pug", name: "Pug" },
    { key: "puggle", name: "Puggle" },
    { key: "puli", name: "Puli" },
    { key: "pumi", name: "Pumi" },
    { key: "pyrenean-mastiff", name: "Pyrenean Mastiff" },
    { key: "pyrenean-shepherd", name: "Pyrenean Shepherd" },
    { key: "rat-terrier", name: "Rat Terrier" },
    { key: "redbone-coonhound", name: "Redbone Coonhound" },
    { key: "rhodesian-ridgeback", name: "Rhodesian Ridgeback" },
    { key: "rottweiler", name: "Rottweiler" },
    { key: "russian-toy", name: "Russian Toy" },
    { key: "saint-bernard", name: "Saint Bernard" },
    { key: "saluki", name: "Saluki" },
    { key: "samoyed", name: "Samoyed" },
    { key: "schapendoes", name: "Schapendoes" },
    { key: "schipperke", name: "Schipperke" },
    { key: "schnoodle", name: "Schnoodle" },
    { key: "scottish-deerhound", name: "Scottish Deerhound" },
    { key: "scottish-terrier", name: "Scottish Terrier" },
    { key: "sealyham-terrier", name: "Sealyham Terrier" },
    { key: "segugio-italiano", name: "Segugio Italiano" },
    { key: "sheepadoodle", name: "Sheepadoodle" },
    { key: "shetland-sheepdog", name: "Shetland Sheepdog" },
    { key: "shiba-inu", name: "Shiba Inu" },
    { key: "shih-tzu", name: "Shih Tzu" },
    { key: "shikoku", name: "Shikoku" },
    { key: "siberian-husky", name: "Siberian Husky" },
    { key: "silky-terrier", name: "Silky Terrier" },
    { key: "skye-terrier", name: "Skye Terrier" },
    { key: "sloughi", name: "Sloughi" },
    { key: "small-munsterlander", name: "Small Munsterlander" },
    { key: "smooth-fox-terrier", name: "Smooth Fox Terrier" },
    { key: "soft-coated-wheaten-terrier", name: "Soft Coated Wheaten Terrier" },
    { key: "spanish-mastiff", name: "Spanish Mastiff" },
    { key: "spanish-water-dog", name: "Spanish Water Dog" },
    { key: "spinone-italiano", name: "Spinone Italiano" },
    { key: "stabyhoun", name: "Stabyhoun" },
    { key: "staffordshire-bull-terrier", name: "Staffordshire Bull Terrier" },
    { key: "standard-schnauzer", name: "Standard Schnauzer" },
    { key: "sussex-spaniel", name: "Sussex Spaniel" },
    { key: "swedish-lapphund", name: "Swedish Lapphund" },
    { key: "swedish-vallhund", name: "Swedish Vallhund" },
    { key: "taiwan-dog", name: "Taiwan Dog" },
    { key: "thai-ridgeback", name: "Thai Ridgeback" },
    { key: "tibetan-mastiff", name: "Tibetan Mastiff" },
    { key: "tibetan-spaniel", name: "Tibetan Spaniel" },
    { key: "tibetan-terrier", name: "Tibetan Terrier" },
    { key: "tornjak", name: "Tornjak" },
    { key: "tosa", name: "Tosa" },
    { key: "toy-fox-terrier", name: "Toy Fox Terrier" },
    { key: "transylvanian-hound", name: "Transylvanian Hound" },
    { key: "treeing-walker-coonhound", name: "Treeing Walker Coonhound" },
    { key: "vizsla", name: "Vizsla" },
    { key: "volpino-italiano", name: "Volpino Italiano" },
    { key: "weimaraner", name: "Weimaraner" },
    { key: "welsh-springer-spaniel", name: "Welsh Springer Spaniel" },
    { key: "welsh-terrier", name: "Welsh Terrier" },
    { key: "west-highland-white-terrier", name: "West Highland White Terrier" },
    { key: "whippet", name: "Whippet" },
    { key: "wire-fox-terrier", name: "Wire Fox Terrier" },
    { key: "wirehaired-pointing-griffon", name: "Wirehaired Pointing Griffon" },
    { key: "wirehaired-vizsla", name: "Wirehaired Vizsla" },
    { key: "xoloitzcuintli", name: "Xoloitzcuintli" },
    { key: "yakutian-laika", name: "Yakutian Laika" },
    { key: "yorkipoo", name: "Yorkipoo" },
    { key: "yorkshire-terrier", name: "Yorkshire Terrier" },
  ],
  cat: [
    { key: "mixed", name: "Mixed / rescue" },
    { key: "domestic-shorthair", name: "Domestic shorthair" },
    { key: "domestic-longhair", name: "Domestic longhair" },
    { key: "abyssinian", name: "Abyssinian" },
    { key: "aegean", name: "Aegean" },
    { key: "american-bobtail", name: "American Bobtail" },
    { key: "american-curl", name: "American Curl" },
    { key: "american-shorthair", name: "American Shorthair" },
    { key: "american-wirehair", name: "American Wirehair" },
    { key: "arabian-mau", name: "Arabian Mau" },
    { key: "australian-mist", name: "Australian Mist" },
    { key: "balinese", name: "Balinese" },
    { key: "bengal", name: "Bengal" },
    { key: "birman", name: "Birman" },
    { key: "bombay", name: "Bombay" },
    { key: "british-longhair", name: "British Longhair" },
    { key: "british-shorthair", name: "British Shorthair" },
    { key: "burmese", name: "Burmese" },
    { key: "burmilla", name: "Burmilla" },
    { key: "chartreux", name: "Chartreux" },
    { key: "chausie", name: "Chausie" },
    { key: "colorpoint-shorthair", name: "Colorpoint Shorthair" },
    { key: "cornish-rex", name: "Cornish Rex" },
    { key: "cymric", name: "Cymric" },
    { key: "devon-rex", name: "Devon Rex" },
    { key: "donskoy", name: "Donskoy" },
    { key: "egyptian-mau", name: "Egyptian Mau" },
    { key: "european-burmese", name: "European Burmese" },
    { key: "european-shorthair", name: "European Shorthair" },
    { key: "exotic-shorthair", name: "Exotic Shorthair" },
    { key: "german-rex", name: "German Rex" },
    { key: "havana-brown", name: "Havana Brown" },
    { key: "highlander", name: "Highlander" },
    { key: "himalayan", name: "Himalayan" },
    { key: "japanese-bobtail", name: "Japanese Bobtail" },
    { key: "khao-manee", name: "Khao Manee" },
    { key: "korat", name: "Korat" },
    { key: "kurilian-bobtail", name: "Kurilian Bobtail" },
    { key: "laperm", name: "LaPerm" },
    { key: "lykoi", name: "Lykoi" },
    { key: "maine-coon", name: "Maine Coon" },
    { key: "manx", name: "Manx" },
    { key: "minuet", name: "Minuet (Napoleon)" },
    { key: "munchkin", name: "Munchkin" },
    { key: "nebelung", name: "Nebelung" },
    { key: "norwegian-forest-cat", name: "Norwegian Forest Cat" },
    { key: "ocicat", name: "Ocicat" },
    { key: "oriental-longhair", name: "Oriental Longhair" },
    { key: "oriental-shorthair", name: "Oriental Shorthair" },
    { key: "persian", name: "Persian" },
    { key: "peterbald", name: "Peterbald" },
    { key: "pixie-bob", name: "Pixie-bob" },
    { key: "ragamuffin", name: "Ragamuffin" },
    { key: "ragdoll", name: "Ragdoll" },
    { key: "russian-blue", name: "Russian Blue" },
    { key: "savannah", name: "Savannah" },
    { key: "scottish-fold", name: "Scottish Fold" },
    { key: "scottish-straight", name: "Scottish Straight" },
    { key: "selkirk-rex", name: "Selkirk Rex" },
    { key: "serengeti", name: "Serengeti" },
    { key: "siamese", name: "Siamese" },
    { key: "siberian", name: "Siberian" },
    { key: "singapura", name: "Singapura" },
    { key: "snowshoe", name: "Snowshoe" },
    { key: "sokoke", name: "Sokoke" },
    { key: "somali", name: "Somali" },
    { key: "sphynx", name: "Sphynx" },
    { key: "thai", name: "Thai" },
    { key: "tonkinese", name: "Tonkinese" },
    { key: "toyger", name: "Toyger" },
    { key: "turkish-angora", name: "Turkish Angora" },
    { key: "turkish-van", name: "Turkish Van" },
    { key: "ukrainian-levkoy", name: "Ukrainian Levkoy" },
  ],
  hamster: [
    { key: "syrian", name: "Syrian" },
    { key: "roborovski", name: "Roborovski" },
    { key: "campbells-dwarf", name: "Campbell's dwarf" },
    { key: "winter-white", name: "Winter white" },
    { key: "chinese", name: "Chinese" },
  ],
  bird: [
    { key: "budgerigar", name: "Budgerigar" },
    { key: "cockatiel", name: "Cockatiel" },
    { key: "lovebird", name: "Lovebird" },
    { key: "african-grey", name: "African grey" },
    { key: "macaw-blue-and-gold", name: "Macaw (blue-and-gold)" },
    { key: "macaw-scarlet", name: "Macaw (scarlet)" },
    { key: "cockatoo", name: "Cockatoo" },
    { key: "conure-green-cheeked", name: "Conure (green-cheeked)" },
    { key: "conure-sun", name: "Conure (sun)" },
    { key: "parrotlet", name: "Parrotlet" },
    { key: "canary", name: "Canary" },
    { key: "zebra-finch", name: "Zebra finch" },
    { key: "society-finch", name: "Society finch" },
    { key: "dove", name: "Dove" },
    { key: "pigeon", name: "Pigeon" },
    { key: "quaker-parrot", name: "Quaker parrot" },
    { key: "eclectus", name: "Eclectus" },
    { key: "amazon-parrot", name: "Amazon parrot" },
    { key: "caique", name: "Caique" },
    { key: "pionus", name: "Pionus" },
    { key: "senegal-parrot", name: "Senegal parrot" },
    { key: "indian-ringneck", name: "Indian ringneck" },
    { key: "kakariki", name: "Kakariki" },
    { key: "java-sparrow", name: "Java sparrow" },
    { key: "chicken", name: "Chicken (house hen)" },
  ],
  reptile: [
    { key: "green-iguana", name: "Green iguana" },
    { key: "blue-iguana", name: "Blue iguana" },
    { key: "red-iguana", name: "Red iguana" },
    { key: "bearded-dragon", name: "Bearded dragon" },
    { key: "chinese-water-dragon", name: "Chinese water dragon" },
    { key: "leopard-gecko", name: "Leopard gecko" },
    { key: "crested-gecko", name: "Crested gecko" },
    { key: "chameleon-veiled", name: "Chameleon (veiled)" },
    { key: "chameleon-panther", name: "Chameleon (panther)" },
    { key: "blue-tongued-skink", name: "Blue-tongued skink" },
  ],
};

export const COATS = {
  dog: [
    { key: "cream", name: "Cream", body: "#EDD9B8", belly: "#F7EEDC", ear: "#D9BE94" },
    { key: "golden", name: "Golden", body: "#D9A45B", belly: "#F0DCB4", ear: "#A8763B" },
    { key: "red", name: "Rusty Red", body: "#B86B3C", belly: "#E6C49E", ear: "#8C4A26" },
    { key: "chocolate", name: "Chocolate", body: "#6B4A32", belly: "#A9876A", ear: "#4C3221" },
    { key: "black", name: "Midnight Black", body: "#3B3A38", belly: "#6E6A64", ear: "#232220" },
    { key: "black-tan", name: "Black & Tan", body: "#3F3732", belly: "#C98F56", ear: "#262120" },
    { key: "tricolor", name: "Tricolor", body: "#4A403A", belly: "#EFE6D8", ear: "#2E2824" },
    { key: "gray-blue", name: "Storm Gray", body: "#8A8F96", belly: "#C4C8CD", ear: "#5E646C" },
    { key: "white", name: "Snow White", body: "#F1EDE4", belly: "#FAF7F0", ear: "#D8D2C4" },
    { key: "brindle", name: "Brindle Brown", body: "#8A6A48", belly: "#C9A87E", ear: "#5B452F" },
    { key: "merle-gray", name: "Merle Gray", body: "#A3A7AD", belly: "#D4D6DA", ear: "#6B7076" },
    { key: "fawn", name: "Fawn", body: "#D3B089", belly: "#EEDDC2", ear: "#A98659" },
  ],
  cat: [
    { key: "black", name: "Midnight Black", body: "#3A3836", belly: "#6B6762", ear: "#232120" },
    { key: "white", name: "Snow White", body: "#F2EEE6", belly: "#FBF8F2", ear: "#D9D3C6" },
    { key: "gray-blue", name: "Blue Gray", body: "#8C929B", belly: "#C6CAD1", ear: "#61676F" },
    { key: "orange-tabby", name: "Orange Tabby", body: "#D98E4A", belly: "#F2D8B8", ear: "#A96630" },
    { key: "brown-tabby", name: "Brown Tabby", body: "#8A6B4D", belly: "#C8B090", ear: "#5C4530" },
    { key: "cream", name: "Cream", body: "#EBD9B9", belly: "#F6EEDC", ear: "#CDB28A" },
    { key: "calico", name: "Calico", body: "#E8DCCB", belly: "#F7F1E6", ear: "#B4753F" },
    { key: "tortoiseshell", name: "Tortoiseshell", body: "#5C4434", belly: "#B9875A", ear: "#3C2B20" },
    { key: "seal-point", name: "Seal Point", body: "#E4D6C2", belly: "#F3EADC", ear: "#5A4436" },
    { key: "lilac", name: "Lilac", body: "#C3B2B2", belly: "#E4DAD8", ear: "#93807F" },
    { key: "tuxedo", name: "Tuxedo", body: "#35332F", belly: "#F3EFE6", ear: "#211F1C" },
    { key: "silver-tabby", name: "Silver Tabby", body: "#B9BCC0", belly: "#E2E4E7", ear: "#7F8389" },
  ],
  hamster: [
    { key: "golden", name: "Golden", body: "#D6A35C", belly: "#F2E2C4", ear: "#A87A3C" },
    { key: "cream", name: "Cream", body: "#EBD9BA", belly: "#F7EFDF", ear: "#CFB58C" },
    { key: "white", name: "Snow White", body: "#F3EFE7", belly: "#FBF9F3", ear: "#D9D2C3" },
    { key: "gray", name: "Dusty Gray", body: "#A8A5A0", belly: "#D6D4CF", ear: "#7B7872" },
    { key: "sable", name: "Sable", body: "#5E4A38", belly: "#A68E72", ear: "#3F3023" },
    { key: "banded-brown", name: "Banded Brown", body: "#9C7046", belly: "#EFE7D8", ear: "#6F4D2D" },
    { key: "cinnamon", name: "Cinnamon", body: "#C98B58", belly: "#EFDCC2", ear: "#9A6436" },
    { key: "dove", name: "Dove", body: "#B3A49C", belly: "#DFD6D0", ear: "#85766E" },
    { key: "champagne", name: "Champagne", body: "#D9C3A8", belly: "#F1E6D5", ear: "#B2946F" },
    { key: "black", name: "Midnight Black", body: "#3E3B38", belly: "#74706B", ear: "#262321" },
  ],
  bird: [
    { key: "green", name: "Meadow Green", body: "#8AA85C", belly: "#DCE6BE", ear: "#5F7C3B" },
    { key: "blue", name: "Sky Blue", body: "#7D9BB8", belly: "#CBDAE6", ear: "#52708C" },
    { key: "yellow", name: "Sunny Yellow", body: "#E3C65E", belly: "#F5EBBE", ear: "#B7983A" },
    { key: "white", name: "Snow White", body: "#F2EFE7", belly: "#FBF9F2", ear: "#D6D1C3" },
    { key: "gray", name: "Dove Gray", body: "#9B9790", belly: "#D4D1CB", ear: "#6E6A63" },
    { key: "teal", name: "Lagoon Teal", body: "#5E9490", belly: "#BBD8D4", ear: "#3D6B67" },
    { key: "peach", name: "Peach Cheek", body: "#E8B48A", belly: "#F6E0C8", ear: "#C27B45" },
    { key: "red", name: "Sunset Red", body: "#B85348", belly: "#E6B8AE", ear: "#8A382F" },
    { key: "rainbow", name: "Rainbow", body: "#6FA06B", belly: "#E6D27E", ear: "#4A6FA0" },
    { key: "violet", name: "Dusk Violet", body: "#9B87B0", belly: "#D6CCE0", ear: "#6F5C87" },
  ],
  reptile: [
    { key: "green", name: "Jungle Green", body: "#7E9B5A", belly: "#C9D8A8", ear: "#566F3B" },
    { key: "blue-gray", name: "River Blue", body: "#8FA0A6", belly: "#C9D3D6", ear: "#63737A" },
    { key: "red-orange", name: "Ember Red", body: "#C2703F", belly: "#E8C4A0", ear: "#8F4E24" },
    { key: "sandy", name: "Desert Sand", body: "#D6BC92", belly: "#EFE3C9", ear: "#A98D61" },
    { key: "olive", name: "Olive", body: "#8A8A58", belly: "#CFCFA8", ear: "#5F5F3A" },
    { key: "pastel-yellow", name: "Pastel Sun", body: "#E0CF8A", belly: "#F2EAC6", ear: "#B5A05A" },
    { key: "citrus", name: "Citrus", body: "#D9A050", belly: "#F0DCB4", ear: "#A87430" },
    { key: "moss", name: "Mossy", body: "#6E8057", belly: "#B8C4A4", ear: "#4A593A" },
    { key: "charcoal", name: "Charcoal", body: "#55534E", belly: "#8E8B84", ear: "#35332F" },
    { key: "hypo-peach", name: "Hypo Peach", body: "#E3B795", belly: "#F4E0CE", ear: "#B5855F" },
  ],
};

export const breedName = (species, key) => (BREEDS[species] || []).find((b) => b.key === key)?.name || "";
export const coatOf = (species, key) => (COATS[species] || []).find((c) => c.key === key) || (COATS[species] || [])[0] || { body: "#C9B291", belly: "#EADFC9", ear: "#9A815D" };
