#!/usr/bin/env python3
# Global tourist-destination seed generator (founder, 2026-10-06: "globally we
# need to include ALL the tourist destinations", after Santa Monica Pier turned
# out to be missing — the old seed was ~10 hand-picked icons per city for 273
# cities). Input: a Wikidata harvest CSV (qid,name,category,lat,lng,cc,city,
# sitelinks,radius_m) swept per tourist class with per-class sitelink bars
# calibrated on real mid-tier icons (Santa Monica Pier=16, Pier 39=12,
# La Rambla=13). Emits idempotent guarded SQL in fix_parks.sql style.
# Run: python3 gen_global_seed.py <harvest.csv>  →  data/load_global_tourist_seed.sql
import csv, pathlib, sys

BASE = pathlib.Path(__file__).parent
src = sys.argv[1] if len(sys.argv) > 1 else str(BASE / "data" / "global_harvest.csv")
rows = list(csv.DictReader(open(src)))
q = lambda s: "'" + str(s).replace("'", "''") + "'"

out = ["-- Global tourist seed, generated by scripts/city-icons/gen_global_seed.py. Safe to re-run.",
       "-- Founder bar (2026-10-06): every top destination near anyone, anywhere — fame measured",
       "-- by Wikipedia language editions, not by whether a hand-picked city list remembered it.",
       "CREATE INDEX IF NOT EXISTS idx_attractions_qid ON attractions(qid);"]
kept = 0
for r in rows:
    name = r["name"].strip()[:120]
    cc = r["cc"].strip().upper()
    if not name or not cc or len(cc) != 2: continue  # no country → junk row
    sl = int(r["sitelinks"])
    scope = "world" if sl >= 45 else "national"
    pop = min(sl * 60000, 20000000)
    city = (r["city"].strip() or "")[:80]
    rid = f"icon:{r['qid']}"
    out.append(
      "INSERT OR IGNORE INTO attractions (id,name,category,lat,lng,city,country,source,source_id,footprint_radius_m,tier,scope,qid,sitelinks,popularity) "
      f"SELECT {q(rid)},{q(name)},{q(r['category'])},{r['lat']},{r['lng']},{q(city)},{q(cc)},'global_seed',{q(r['qid'])},{r['radius_m']},'page',{q(scope)},{q(r['qid'])},{sl},{pop} "
      f"WHERE NOT EXISTS (SELECT 1 FROM attractions WHERE qid={q(r['qid'])}) "
      f"AND NOT EXISTS (SELECT 1 FROM attractions WHERE name={q(name)} AND country={q(cc)});")
    kept += 1
dest = BASE / "data" / "load_global_tourist_seed.sql"
dest.write_text("\n".join(out) + "\n")
print(f"wrote {kept} guarded inserts → {dest}")
