#!/usr/bin/env python3
# city-icons loader generator — emits idempotent SQL that INSERTs an icon only
# when no row with its qid (or name+city, when qid is unknown) exists, then
# UPDATEs scope/radius so already-present rows get promoted instead of duped.
# Run: python3 gen_sql.py  →  data/load_city_icons.sql
import csv, pathlib, re
BASE = pathlib.Path(__file__).parent
rows = list(csv.DictReader(open(BASE/"data"/"icons_seed.csv")))
q = lambda s: "'" + str(s).replace("'", "''") + "'"
slug = lambda n: re.sub(r"[^a-z0-9]+", "-", n.lower()).strip("-")[:48]
out = ["-- City icons load, generated by scripts/city-icons/gen_sql.py. Safe to re-run.",
       "-- Founder bar (2026-09-30): every city's suggestions match where tourists actually go.",
       "CREATE INDEX IF NOT EXISTS idx_attractions_qid ON attractions(qid);",
       "CREATE INDEX IF NOT EXISTS idx_attractions_name ON attractions(name);"]
for r in rows:
    name, qid, city = r["name"].strip(), r["qid"].strip(), r["city"].strip()
    rid = f"icon:{qid}" if qid else f"icon:{slug(name)}"
    exists = f"qid={q(qid)}" if qid else f"(name={q(name)} AND city={q(city)})"
    pop = 500000 if r["scope"] == "world" else 200000 if r["scope"] == "national" else 80000
    out.append(
      "INSERT OR IGNORE INTO attractions (id,name,category,lat,lng,city,country,source,source_id,footprint_radius_m,tier,scope,qid,sitelinks,popularity) "
      f"SELECT {q(rid)},{q(name)},{q(r['category'])},{r['lat']},{r['lng']},{q(city)},{q(r['country'])},'city_icon',{q(qid or slug(name))},{r['radius_m']},'page',{q(r['scope'])},{q(qid) if qid else 'NULL'},150,{pop} "
      f"WHERE NOT EXISTS (SELECT 1 FROM attractions WHERE {exists});")
    out.append(
      f"UPDATE attractions SET founder_scope={q(r['scope'])}, footprint_radius_m=coalesce(footprint_radius_m,{r['radius_m']}), popularity=max(coalesce(popularity,0),{pop}), updated_at=datetime('now') WHERE {exists};")
(BASE/"data"/"load_city_icons.sql").write_text("\n".join(out) + "\n")
print(f"wrote {len(rows)*2} statements for {len(rows)} icons")
