#!/usr/bin/env python3
"""Emit D1 INSERT-OR-REPLACE SQL for the RANKED attractions layer.

Like scripts/emit_d1_seed.py, but carries the ranking columns (pop_score, pageviews,
sitelinks) added by scripts/attractions-rank/01_alter_pop_score.sql, and stamps
source='ranked'. Reads a curation JSON produced by seed_city.py:
    { "result": { "attractions": [ {name,category,lat,lng,city,country,
                  typical_minutes,is_marquee,free_to_visit,pop_score,pageviews,sitelinks}, ... ] } }

Usage:
  python3 scripts/attractions-rank/emit_ranked_sql.py scripts/attractions-rank/out/seed_attractions.curation.json
  -> writes cloudflare-worker/sql/seed_attractions_ranked.sql

Then load (needs your Cloudflare creds):
  cd "<repo>" && npx wrangler d1 execute globeskimmers-attractions --remote \
    --file cloudflare-worker/sql/seed_attractions_ranked.sql
"""
import json, os, re, sys
from pathlib import Path

VALID = {'museum','landmark','viewpoint','beach','park','national_park','theme_park','zoo',
         'aquarium','art_gallery','historic','religious','market','monument','nature_reserve',
         'waterfall','garden','observation_deck','district','square','palace','tower','cathedral',
         'temple','shrine','mosque','fortress','wildlife','experience','river','lake'}

def slug(s):
    s = re.sub(r'[^a-z0-9]+', '-', (s or '').lower().strip())
    return re.sub(r'-+', '-', s).strip('-')[:80] or 'unknown'

def esc(s):
    return 'NULL' if s is None else "'" + str(s).replace("'", "''") + "'"

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else None
    if not src or not os.path.exists(src):
        print(f"Usage: {sys.argv[0]} <curation.json>", file=sys.stderr); sys.exit(1)
    attractions = json.load(open(src)).get('result', {}).get('attractions', [])
    seen, rows, skipped = set(), [], 0
    for a in attractions:
        if not all(a.get(k) for k in ('name', 'category', 'country')):
            skipped += 1; continue
        lat, lng = a.get('lat'), a.get('lng')
        if not isinstance(lat, (int, float)) or not isinstance(lng, (int, float)) \
           or not (-90 <= lat <= 90) or not (-180 <= lng <= 180):
            skipped += 1; continue
        cat = a['category'] if a['category'] in VALID else 'landmark'
        base = 'curated:' + '-'.join(filter(None, [slug(a['country']), slug(a.get('city', '')), slug(a['name'])]))
        aid, n = base, 2
        while aid in seen:
            aid = f"{base}-{n}"; n += 1
        seen.add(aid)
        rows.append({
            'id': aid, 'name': a['name'], 'category': cat, 'lat': lat, 'lng': lng,
            'city': a.get('city', '') or '', 'country': a['country'],
            'description': a.get('description', '') or '', 'why_visit': a.get('why_visit', '') or '',
            'typical_minutes': int(a.get('typical_minutes', 60) or 60),
            'is_marquee': 1 if a.get('is_marquee') else 0,
            'free_to_visit': 1 if a.get('free_to_visit') else 0,
            'pop_score': round(float(a.get('pop_score', 0) or 0), 1),
            'pageviews': int(a.get('pageviews', 0) or 0), 'sitelinks': int(a.get('sitelinks', 0) or 0),
        })
    repo = Path(__file__).resolve().parent.parent.parent
    out_path = repo / 'cloudflare-worker' / 'sql' / 'seed_attractions_ranked.sql'
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '-- Auto-generated by scripts/attractions-rank/emit_ranked_sql.py',
        f'-- {len(rows)} ranked attractions across {len({r["city"] for r in rows})} cities.',
        '-- Prereq: run scripts/attractions-rank/01_alter_pop_score.sql once first.',
        '-- INSERT OR REPLACE = idempotent re-seed. No BEGIN/COMMIT (D1 wraps each file).',
        '',
    ]
    for r in rows:
        lines.append(
            "INSERT OR REPLACE INTO attractions (id,name,category,lat,lng,city,country,"
            "description,why_visit,typical_minutes,rating,is_marquee,free_to_visit,"
            "pop_score,pageviews,sitelinks,source,last_reviewed) VALUES ("
            f"{esc(r['id'])},{esc(r['name'])},{esc(r['category'])},{r['lat']:.6f},{r['lng']:.6f},"
            f"{esc(r['city'])},{esc(r['country'])},{esc(r['description'])},{esc(r['why_visit'])},"
            f"{r['typical_minutes']},NULL,{r['is_marquee']},{r['free_to_visit']},"
            f"{r['pop_score']},{r['pageviews']},{r['sitelinks']},'ranked',date('now'));")
    lines.append('')
    out_path.write_text('\n'.join(lines))
    print(f"Kept {len(rows)} rows (skipped {skipped}). Wrote {out_path}")

if __name__ == '__main__':
    main()
