#!/usr/bin/env python3
"""Emit cloudflare-worker/sql/seed_attractions.sql from a workflow output JSON.

Usage:
  python3 scripts/emit_d1_seed.py <workflow-output-json>

Reads the workflow result, applies a few hardening passes (slug
generation, range validation, deduplication), and writes both the SQL
INSERT file (for `wrangler d1 execute`) and a JSON copy (for any
non-SQL fallback we might want later).
"""

import json
import re
import sys
import os
from pathlib import Path

# Categories the schema enum accepts. Anything outside this list gets
# folded into 'landmark' as a safe default so a stray category from the
# curation pass doesn't blow up the INSERT.
VALID_CATEGORIES = {
    'museum','landmark','viewpoint','beach','park','national_park',
    'theme_park','zoo','aquarium','art_gallery','historic','religious',
    'market','monument','nature_reserve','waterfall','garden',
    'observation_deck','district','square','palace','tower','cathedral',
    'temple','shrine','mosque','fortress','wildlife','experience',
    'river','lake',
}

def slugify(name: str) -> str:
    """Stable, URL-safe id slug. Same name always → same slug."""
    s = name.lower().strip()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    s = re.sub(r'-+', '-', s).strip('-')
    return s[:80] if s else 'unknown'

def sql_escape(s: str) -> str:
    """SQLite single-quote escape — double up any apostrophes."""
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else None
    if not src or not os.path.exists(src):
        print(f"Usage: {sys.argv[0]} <workflow-output.json>", file=sys.stderr)
        sys.exit(1)

    with open(src) as f:
        data = json.load(f)

    result = data.get('result', {})
    attractions = result.get('attractions', [])

    print(f"Read {len(attractions)} attractions from {src}")

    # Hardening passes
    seen_ids = set()
    rows = []
    skipped = 0
    for a in attractions:
        # Required fields
        if not all(a.get(k) for k in ('name', 'category', 'country')):
            skipped += 1
            continue
        lat = a.get('lat')
        lng = a.get('lng')
        if not isinstance(lat, (int, float)) or not isinstance(lng, (int, float)):
            skipped += 1
            continue
        if not (-90 <= lat <= 90) or not (-180 <= lng <= 180):
            skipped += 1
            continue

        cat = a['category']
        if cat not in VALID_CATEGORIES:
            cat = 'landmark'

        # Build a stable id
        slug_parts = [a['country'].lower().replace(' ', '-')]
        if a.get('city'):
            slug_parts.append(a['city'].lower().replace(' ', '-'))
        slug_parts.append(slugify(a['name']))
        base_id = 'curated:' + '-'.join(slug_parts)

        # Dedupe by id (workflow already deduped by name+country, but a
        # belt-and-suspenders pass here covers any case where two
        # curators independently named the same place identically)
        attr_id = base_id
        counter = 2
        while attr_id in seen_ids:
            attr_id = f"{base_id}-{counter}"
            counter += 1
        seen_ids.add(attr_id)

        rows.append({
            'id': attr_id,
            'name': a['name'],
            'category': cat,
            'lat': lat,
            'lng': lng,
            'city': a.get('city', '') or '',
            'country': a['country'],
            'description': a.get('description', '') or '',
            'why_visit': a.get('why_visit', '') or '',
            'typical_minutes': int(a.get('typical_minutes', 60) or 60),
            'rating': None,  # not set during curation; populated later
            'is_marquee': 1 if a.get('is_marquee') else 0,
            'free_to_visit': 1 if a.get('free_to_visit') else 0,
        })

    print(f"Kept {len(rows)} valid rows, skipped {skipped}")

    # Emit SQL
    repo_root = Path(__file__).resolve().parent.parent
    sql_path = repo_root / 'cloudflare-worker' / 'sql' / 'seed_attractions.sql'
    sql_path.parent.mkdir(parents=True, exist_ok=True)

    out = []
    out.append('-- Auto-generated by scripts/emit_d1_seed.py from')
    out.append(f'-- workflow output {os.path.basename(src)}.')
    out.append('-- Do not edit by hand; re-run the workflow + emitter to refresh.')
    out.append('--')
    out.append(f"-- {len(rows)} attractions across {len({r['country'] for r in rows})} countries.")
    out.append('--')
    out.append("-- INSERT OR REPLACE means re-running the seed is idempotent — safe")
    out.append("-- to re-execute against an already-seeded database, will update any")
    out.append("-- rows whose content changed and add any new rows.")
    out.append('--')
    out.append('-- No BEGIN TRANSACTION / COMMIT here on purpose — Cloudflare D1')
    out.append('-- rejects SQL-level transaction control with')
    out.append("--   ERROR: To execute a transaction, please use the state.storage")
    out.append('--          .transaction() ... APIs instead of the SQL BEGIN TRANSACTION')
    out.append('-- D1 wraps each --file execution in its own atomic operation, so the')
    out.append('-- bare INSERT OR REPLACE statements below are still applied as a')
    out.append('-- single unit. An error mid-file rolls the whole thing back.')
    out.append('')

    for r in rows:
        sql = (
            "INSERT OR REPLACE INTO attractions "
            "(id, name, category, lat, lng, city, country, description, "
            "why_visit, typical_minutes, rating, is_marquee, free_to_visit, "
            "source, last_reviewed) VALUES ("
            f"{sql_escape(r['id'])}, "
            f"{sql_escape(r['name'])}, "
            f"{sql_escape(r['category'])}, "
            f"{r['lat']:.6f}, "
            f"{r['lng']:.6f}, "
            f"{sql_escape(r['city'])}, "
            f"{sql_escape(r['country'])}, "
            f"{sql_escape(r['description'])}, "
            f"{sql_escape(r['why_visit'])}, "
            f"{r['typical_minutes']}, "
            f"{'NULL' if r['rating'] is None else r['rating']}, "
            f"{r['is_marquee']}, "
            f"{r['free_to_visit']}, "
            "'curated', "
            "date('now')"
            ");"
        )
        out.append(sql)

    out.append('')

    sql_path.write_text('\n'.join(out))
    print(f"Wrote {sql_path}")

    # Also emit a clean JSON copy for any in-memory fallback we want
    json_path = repo_root / 'cloudflare-worker' / 'sql' / 'seed_attractions.json'
    json_path.write_text(json.dumps({
        'meta': {
            'count': len(rows),
            'marquee': sum(1 for r in rows if r['is_marquee']),
            'countries': sorted({r['country'] for r in rows}),
            'cities': sorted({r['city'] for r in rows if r['city']}),
        },
        'attractions': rows,
    }, indent=2, ensure_ascii=False))
    print(f"Wrote {json_path}")

if __name__ == '__main__':
    main()
