#!/usr/bin/env node
// emit-seed.mjs — stage 5: turn resolved attractions into ATTRACTIONS_DB seed SQL.
//
//   node emit-seed.mjs RESOLVED_DIR OUT_SQL_FILE
//
// Emits INSERT OR REPLACE rows for the D1 `attractions` table (schema.sql +
// 02_seed_columns.sql). Design decisions, each argued elsewhere in the pipeline:
//
// * id: "wikidata:<qid>" where known — the format schema.sql documents for bulk
//   imports — else "wv:<city>-<name>" slug. Stable across re-runs.
// * description/why_visit stay EMPTY: Wikivoyage prose is CC BY-SA and shipping
//   it would make our text share-alike. Names/coords/structure are facts.
// * category maps Overture types onto the enum schema.sql documents — browse
//   queries filter `category IN (...)`, so unmapped categories would make rows
//   invisible (the exact T1.6 failure class).
// * footprint_radius_m mirrors src/lib/stampRadius.js so the ✓ circle comes
//   from data; the client heuristic stays as fallback for Google-sourced places.
// * is_marquee: top 3 per city ("you cannot visit without seeing this").
// * popularity = median monthly pageviews; NULL rows sort after ranked ones.

import fs from "node:fs";
import path from "node:path";

const [RESOLVED, OUT_SQL] = process.argv.slice(2);
if (!RESOLVED || !OUT_SQL) { console.error("usage: node emit-seed.mjs RESOLVED_DIR OUT_SQL_FILE"); process.exit(1); }

const slug = (s) => String(s || "").normalize("NFKD").replace(/[̀-ͯ]/g, "")
  .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);
const q = (s) => s == null ? "NULL" : `'${String(s).replace(/'/g, "''")}'`;
const n = (v) => (v == null || Number.isNaN(v)) ? "NULL" : String(v);

// Overture/Wikivoyage → the category enum schema.sql documents.
const CAT = [
  [/amusement_park|theme_park|water_park/, "theme_park"],
  [/national_park/, "national_park"],
  [/nature_reserve|wildlife/, "nature_reserve"],
  [/museum/, "museum"],
  [/art_galler/, "art_gallery"],
  [/aquarium/, "aquarium"],
  [/zoo/, "zoo"],
  [/castle|fortress|citadel/, "fortress"],
  [/palace/, "palace"],
  [/cathedral/, "cathedral"],
  [/mosque/, "mosque"],
  [/shrine/, "shrine"],
  [/temple|monastery|church|place_of_worship|basilica|religious/, "religious"],
  [/cemetery|memorial|monument/, "monument"],
  [/viewpoint|observation/, "viewpoint"],
  [/beach/, "beach"],
  [/waterfall/, "waterfall"],
  [/garden|botanical/, "garden"],
  [/park/, "park"],
  [/market|bazaar|souk/, "market"],
  [/square|plaza/, "square"],
  [/tower/, "tower"],
  [/bridge|historical|historic|heritage|landmark|archaeolog|ruin/, "historic"],
  [/stadium|arena/, "experience"],
  [/lake/, "lake"],
  [/river|canal/, "river"],
];
const category = (r) => {
  const hay = `${r.place_category || ""} ${r.section || ""}`.toLowerCase();
  for (const [re, c] of CAT) if (re.test(hay)) return c;
  return r.type === "do" ? "experience" : "landmark";
};

// Mirrors src/lib/stampRadius.js — the ✓ circle sized by kind of place.
const FOOT = [
  [/national_park|nature_reserve/, 6000], [/beach|lake|waterfall/, 1800],
  [/theme_park/, 900], [/zoo|aquarium|garden|viewpoint|park$/, 600],
  [/market|square|fortress|palace/, 400],
];
const footprint = (cat) => { for (const [re, m] of FOOT) if (re.test(cat)) return m; return null; };

const cities = fs.readFileSync(path.join(RESOLVED, "resolved.jsonl"), "utf8")
  .split("\n").filter(Boolean).map((l) => JSON.parse(l));

const today = new Date().toISOString().slice(0, 10);
const lines = [
  `-- Generated by scripts/attractions-seed/emit-seed.mjs on ${today}`,
  `-- Source: Wikivoyage listings (CC BY-SA facts only — no prose shipped),`,
  `-- ranked by Wikipedia pageviews, cleaned by Wikidata type, resolved onto`,
  `-- the owned Overture places. Run AFTER 02_seed_columns.sql:`,
  `--   npx wrangler d1 execute globeskimmers-attractions --file=<this file> --remote`,
  ``,
];
let emitted = 0, skipped = 0;

for (const c of cities) {
  // Country: from the owned row when matched, else the city's majority answer.
  const counts = {};
  for (const r of c.top) if (r.place_country) counts[r.place_country] = (counts[r.place_country] || 0) + 1;
  const majority = Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0] || null;

  lines.push(`-- ── ${c.city} ${"─".repeat(Math.max(2, 40 - c.city.length))}`);
  for (const r of c.top) {
    const country = r.place_country || majority;
    if (!Number.isFinite(r.lat) || !Number.isFinite(r.lng) || !country) { skipped++; continue; }
    const id = r.qid ? `wikidata:${r.qid}` : `wv:${slug(c.city)}-${slug(r.name)}`;
    const cat = category(r);
    lines.push(
      `INSERT OR REPLACE INTO attractions (id, name, category, lat, lng, city, country, ` +
      `typical_minutes, is_marquee, free_to_visit, source, source_id, last_reviewed, ` +
      `popularity, place_id, footprint_radius_m, tier) VALUES (` +
      [q(id), q(r.name), q(cat), n(r.lat), n(r.lng), q(r.place_city || c.city), q(country),
       "60", r.rank <= 3 ? "1" : "0", "0", q("wikivoyage"), q(r.page), q(today),
       n(r.pv), q(r.place_id ?? null), n(footprint(cat)), q("page")].join(", ") + ");");
    emitted++;
  }
  lines.push("");
}
fs.writeFileSync(OUT_SQL, lines.join("\n"));
console.error(`DONE — ${emitted} rows emitted, ${skipped} skipped (no coords or no country) → ${OUT_SQL}`);
