"""One plain sentence per curated claim, written ONLY from the evidence sentences
in curated_evidence.csv (Wikipedia, fetched 2026-09-28). Where the evidence says no
more than "filmed here", the line says no more than that and the row is flagged
scene_generic for the next (scene-writing) phase.

Key: (spot key, work article) where spot key = the entry's qid if given, else its article.
"""
G = "scene_generic"
S = {
    ("Q13024284", "The Beach (film)"): "The film's hidden paradise beach; the crew landscaped the bay to look more \"paradise-like\".",
    ("Khao Phing Kan", "The Man with the Golden Gun (film)"): "Scaramanga's island hideout - the reason Khao Phing Kan and Ko Tapu are called James Bond Island.",
    ("Ta Prohm", "Lara Croft: Tomb Raider"): "Portions of the film were shot at the temple, now nicknamed the \"Tomb Raider Temple\".",
    ("Angkor Wat", "In the Mood for Love"): "The final sequence: Chow, now a journalist in Cambodia, visits Angkor Wat.",
    ("Hạ Long Bay", "Kong: Skull Island"): ("Location filming for the film took place in the bay.", G),
    ("Hạ Long Bay", "Indochine (film)"): ("One of the main Vietnamese locations where the film was shot.", G),
    ("Tràng An", "Kong: Skull Island"): ("Location filming for the film took place among these karst landscapes.", G),
    ("Tú Làn Caves System", "Kong: Skull Island"): ("The entrance of the cave system was a filming location for the film.", G),
    ("Padang Padang Beach", "Eat Pray Love"): ("One of the film's filming locations in Bali.", G),
    ("Petronas Towers", "Entrapment (film)"): "The heist target: the bank inside the towers, hit as the millennium New Year's Eve celebrations begin.",
    ("Marina Bay Sands", "Crazy Rich Asians (film)"): "The film's closing scenes are set at the hotel.",
    ("Q120450702", "Crazy Rich Asians (film)"): "After the wedding, the reception is held in the Supertree Grove.",
    ("Newton Food Centre", "Crazy Rich Asians (film)"): "Colin and Araminta whisk Rachel and Nick from the airport straight to this hawker centre.",
    ("Raffles Hotel", "Crazy Rich Asians (film)"): "Rachel and Nick stay here on arriving in Singapore; the hotel scenes were shot on location.",
    ("CHIJMES", "Crazy Rich Asians (film)"): "Colin and Araminta's wedding was shot in CHIJMES Hall, a former convent.",
    ("Cheong Fatt Tze Mansion", "Indochine (film)"): ("Some parts of the film were shot in the mansion.", G),
    ("Cheong Fatt Tze Mansion", "Crazy Rich Asians (film)"): "Eleanor's mahjong showdown with Rachel was filmed here, the mansion redecorated as a mahjong parlour.",
    ("Kellie's Castle", "Anna and the King"): ("The castle was used as a setting in the film.", G),
    ("Hotel Continental Saigon", "The Quiet American (2002 film)"): "The hotel features prominently in the film, as it does in Graham Greene's novel.",
    ("Hotel Continental Saigon", "Indochine (film)"): "A central locale in the film.",
    ("Kitulgala", "The Bridge on the River Kwai"): "The film's bridge stood on the Kelani River near here; only its concrete foundations remain.",
    ("Chhatrapati Shivaji Terminus", "Slumdog Millionaire"): "The \"Jai Ho\" dance number was filmed at the station.",
    ("Lake Palace", "Octopussy"): "Octopussy's island palace home.",
    ("Jag Mandir", "Octopussy"): "Scenes set at Octopussy's palace were filmed here and at the Lake Palace.",
    ("Monsoon Palace", "Octopussy"): "The exterior of the villain Kamal Khan's palace.",
    ("City Palace, Udaipur", "Octopussy"): "Bond's hotel in Udaipur: the palace appears as the hotel where he stays.",
    ("Mehrangarh", "The Dark Knight Rises"): "Principal photography for the film began at the fort in May 2011.",
    ("Mehrangarh", "The Jungle Book (1994 film)"): ("One of the filming locations for Disney's live-action film.", G),
    ("Pangong Tso", "3 Idiots"): "The film's climax was shot at the lake.",
    ("Druk White Lotus School", "3 Idiots"): ("Scenes of the film were shot at the school.", G),
    ("Ramanagara", "Sholay"): "Much of the film was shot over two and a half years in the rocky hills here, nicknamed the Sholay hills.",
    ("Jaisalmer Fort", "Sonar Kella"): "Satyajit Ray filmed his Golden Fortress story here - the film gave the fort its popular name, Sonar Kella.",
    ("Nahargarh Fort", "Rang De Basanti"): "One of the film's songs was shot at the fort overlooking Jaipur.",
    ("Dudhsagar Falls", "Chennai Express"): "A romantic scene aboard a train passing the falls was shot here.",
    ("Athirappilly Falls", "Baahubali: The Beginning"): "The film's waterfall scenes were shot here.",
    ("Ramoji Film City", "Baahubali: The Beginning"): "The huge Mahishmati kingdom sets were built here and are part of the film city's tour.",
    ("Betaab Valley", "Betaab"): "The valley was named after the 1983 film shot here.",
    ("Chapora Fort", "Dil Chahta Hai"): "The trio's scene at the fort became iconic and made it one of Goa's prime attractions.",
    ("Howrah Bridge", "Lion (2016 film)"): "Young Saroo lives near the bridge for two months before being taken to an orphanage.",
    ("Howrah Bridge", "Howrah Bridge (film)"): "The bridge features in the 1958 thriller named after it.",
    ("Rinpung Dzong", "Little Buddha"): "Several scenes of the film were filmed at the dzong.",
    ("Forbidden City", "The Last Emperor"): "The first Western feature allowed to film inside: the toddler Puyi is summoned here to become emperor.",
    ("Jiuzhaigou", "Hero (2002 film)"): "The film's lake sequences were shot here.",
    ("Hongcun", "Crouching Tiger, Hidden Dragon"): ("Scenes of the film were filmed on location in the village.", G),
    ("Xitang", "Mission: Impossible III"): "The water town appears in the film's final sequences.",
    ("Hengdian World Studios", "Hero (2002 film)"): "The studio's palace set was the backdrop for Emperor Qin's palace.",
    ("Chungking Mansions", "Chungking Express"): "The building gives the film its title; much of the first story takes place here.",
    ("Central–Mid-Levels escalator", "Chungking Express"): "Wong Kar-wai filmed along the escalator, finding its light \"entirely appropriate\".",
    ("Central–Mid-Levels escalator", "The Dark Knight"): ("Part of the film's Hong Kong shoot took place on the escalator.", G),
    ("Yick Cheong Building", "Transformers: Age of Extinction"): ("The housing block inspired locations in the film.", G),
    ("Two International Finance Centre", "The Dark Knight"): "Batman leaps from 2 IFC to 1 IFC.",
    ("The Peninsula Hong Kong", "The Dark Knight"): "A scene with Lucius Fox and Lau was filmed at the hotel.",
    ("Jiufen", "A City of Sadness"): "The film was shot on location in the old mining town; tea houses named after it followed.",
    ("Park Hyatt Tokyo", "Lost in Translation (film)"): "Bob stays at the hotel; its rooms, bar and pool were used for filming.",
    ("Shibuya Crossing", "Lost in Translation (film)"): "Filmed at the crossing, including the \"walking dinosaur\" video screen scene.",
    ("Fushimi Inari-taisha", "Memoirs of a Geisha (film)"): "Some scenes were shot at the shrine near the end of production.",
    ("Kiyomizu-dera", "Memoirs of a Geisha (film)"): ("One of the Kyoto temples where the film was shot on location.", G),
    ("Himeji Castle", "You Only Live Twice (film)"): "The castle was depicted as Tanaka's ninja training camp.",
    ("Engyō-ji", "The Last Samurai"): ("The mountain temple was used as a filming location.", G),
    ("Shinmoedake", "You Only Live Twice (film)"): "The volcano that hides SPECTRE's secret rocket base.",
    ("Suga Shrine (Shinjuku)", "Your Name"): "The closing scene: Taki and Mitsuha meet on the shrine stairs and ask each other's names.",
    ("Shinjuku Gyoen", "The Garden of Words"): "Takao and Yukari keep meeting in the garden on rainy mornings; the film's garden is modelled on it.",
    ("Q119693119", "Slam Dunk (manga)"): "The railway crossing features prominently in the anime's theme-song sequence.",
    ("Namiseom", "Winter Sonata"): "The drama was filmed mainly on the island; visitors rose from 250,000 to over 650,000 after it aired.",
    ("Mona Yongpyong", "Winter Sonata"): "Some scenes of the drama were filmed at the ski resort.",
    ("Mona Yongpyong", "Guardian: The Lonely and Great God"): ("The resort was featured in the drama.", G),
    ("Wadi Rum", "Lawrence of Arabia (film)"): "David Lean filmed much of the film's desert on location here.",
    ("Wadi Rum", "The Martian (film)"): "The valley stood in for the surface of Mars.",
    ("Wadi Rum", "Rogue One"): "Used for scenes set on Jedha.",
    ("Wadi Rum", "Prometheus (2012 film)"): "Scenes for the alien planet were filmed in the valley.",
    ("Al-Khazneh", "Indiana Jones and the Last Crusade"): "The Treasury's facade stands in for the temple housing the Holy Grail.",
    ("Burj Khalifa", "Mission: Impossible – Ghost Protocol"): "Ethan Hunt climbs the outside of the tower - Cruise was really on the building, secured by cables.",
    ("Emirates Palace", "Furious 7"): ("The hotel served as a filming location for the film.", G),
    ("Liwa Oasis", "Star Wars: The Force Awakens"): "The desert east of the oasis stood in for the desert planet Jakku.",
    ("Grand Bazaar, Istanbul", "Skyfall"): ("The bazaar was closed for filming during the film's Istanbul shoot.", G),
    ("Spice Bazaar", "Skyfall"): ("The bazaar was closed for filming during the film's Istanbul shoot.", G),
    ("Varda Viaduct", "Skyfall"): "The opening train chase crosses the viaduct; a stunt double dived backwards off the 300-foot drop.",
    ("Basilica Cistern", "From Russia with Love (film)"): ("The cistern was a location for the 1963 Bond film.", G),
    ("Basilica Cistern", "Inferno (2016 film)"): "The hidden weapon is traced to a bag underwater in the cistern.",
    ("Hagia Sophia", "From Russia with Love (film)"): ("One of the film's Istanbul locations.", G),
    ("Sirkeci railway station", "From Russia with Love (film)"): "The station also played the film's Belgrade and Zagreb stations.",
    ("Maiden's Tower", "The World Is Not Enough"): "Renard's hideout in Turkey, where Bond traces the locator card.",
    ("Küçüksu Palace", "The World Is Not Enough"): "Exteriors of Elektra King's villa in Baku were shot at the pavilion.",
    ("Avdat", "Jesus Christ Superstar (film)"): "The abandoned Nabataean city was used for the scenes with the priests.",
    ("Aït Benhaddou", "Gladiator (2000 film)"): ("One of the many films shot at the ksar.", G),
    ("Aït Benhaddou", "Lawrence of Arabia (film)"): ("One of the many films shot at the ksar.", G),
    ("Aït Benhaddou", "Game of Thrones"): ("The ksar was used in parts of the series.", G),
    ("Atlas Studios", "Kingdom of Heaven (film)"): ("The studio outside Ouarzazate is where many of the area's films were made.", G),
    ("Q131315947", "Star Wars (film)"): "The scenes of Luke Skywalker's Tatooine home were filmed at the hotel.",
    ("Ksar Ouled Soltane", "Star Wars: Episode I – The Phantom Menace"): "Stood in for the slave quarters of Mos Espa, where young Anakin lived.",
    ("Ksar Hadada", "Star Wars: Episode I – The Phantom Menace"): "Used to represent Mos Espa on Tatooine, Anakin Skywalker's birthplace.",
    ("Chott el Djerid", "Star Wars (film)"): "Principal photography began on the salt flat in March 1976.",
    ("Ajim", "Star Wars (film)"): ("The town and its surroundings were used as filming locations.", G),
    ("Ribat of Monastir", "Monty Python's Life of Brian"): ("The fortress was used as a location for the film.", G),
    ("Amphitheatre of El Jem", "Monty Python's Life of Brian"): ("The amphitheatre features in the film.", G),
    ("Karnak", "The Spy Who Loved Me (film)"): ("One of the Egyptian sites where the film was shot.", G),
    ("Karnak", "Death on the Nile (1978 film)"): "The travellers are shown visiting the temple, on the same day as Abu Simbel.",
    ("Abu Simbel temples", "Death on the Nile (1978 film)"): "The travellers are shown visiting the temples.",
    ("Abu Simbel temples", "The Spy Who Loved Me (film)"): ("One of the Egyptian sites where the film was shot.", G),
    ("Great Sphinx of Giza", "The Spy Who Loved Me (film)"): "The Sphinx was shot on location; the pyramids behind it were replaced with miniatures.",
    ("Mosque of Ibn Tulun", "The Spy Who Loved Me (film)"): ("Parts of the film were shot at the mosque.", G),
    ("Gayer-Anderson Museum", "The Spy Who Loved Me (film)"): "Scenes were shot in the museum's reception hall and on its rooftop terrace.",
    ("Deadvlei", "The Cell (film)"): ("One of the film's filming locations in Namibia.", G),
    ("Deadvlei", "The Fall (2006 film)"): ("The film was partly shot here.", G),
    ("Kolmanskop", "Dust Devil (film)"): ("The abandoned town was one of the film's locations.", G),
    ("Spitzkoppe", "2001: A Space Odyssey"): "Still photographs of the peaks became the backgrounds of the \"Dawn of Man\" sequence.",
    ("Essaouira", "Game of Thrones"): "The fortified harbour (skala) stood in for the slaver city of Astapor in season three.",
    ("Essaouira", "Othello (1951 film)"): ("Orson Welles stayed in town while filming his Othello.", G),
    ("Mismaloya", "The Night of the Iguana (film)"): "Principal photography took place here over 72 days.",
    ("Zócalo", "Spectre (2015 film)"): "The pre-title sequence: Bond takes over a helicopter above the Day of the Dead crowds in the square.",
    ("Gran Hotel Ciudad de México", "Spectre (2015 film)"): "Day of the Dead festival scenes were filmed in and around the hotel.",
    ("Baja Studios", "Titanic (1997 film)"): "The studio was built for the film; its full-scale Titanic replica was shot in a giant water tank.",
    ("Real de Catorce", "The Mexican"): ("The film was shot in the town.", G),
    ("Eyipantla Falls", "Apocalypto"): "The film's waterfall scene was shot here.",
    ("Tikal Temple IV", "Star Wars (film)"): "A scene for the moon Yavin 4 was shot at the temple.",
    ("Sugarloaf Mountain", "Moonraker (film)"): "Bond and Goodhead are attacked by Jaws on the Sugarloaf cable car.",
    ("Iguazu Falls", "The Mission (1986 film)"): "The film is set around the falls; a missionary priest is thrown to his death from them.",
    ("Iguazu Falls", "Moonraker (film)"): ("The falls feature in the film.", G),
    ("Casa Rosada", "Evita (1996 film)"): "The crew was allowed to film at the palace, setting of the song \"On the Balcony of the Casa Rosada\".",
    ("ESO Hotel", "Quantum of Solace"): "The hotel's exterior plays the \"Perla de las Dunas\" eco-hotel where Bond confronts Greene.",
    ("Salar de Uyuni", "Star Wars: The Last Jedi"): "The salt flat was the location for the battle on the planet Crait.",
    ("Machu Picchu", "Transformers: Rise of the Beasts"): ("The film shot sequences at the citadel.", G),
    ("Angel Falls", "Point Break (2015 film)"): "The free-solo climbing ordeal beside the falls; the crew camped below, on the rim and on the tepui.",
    ("Paraty", "The Twilight Saga: Breaking Dawn – Part 1"): "The honeymoon scenes on Isle Esme were shot here.",
    ("Staniel Cay", "Thunderball (film)"): "The grotto was a setting of the film - and is named after it.",
    ("Indian River (Dominica)", "Pirates of the Caribbean: Dead Man's Chest"): ("Some of the film's scenes were shot on the river.", G),
    ("Marigot Bay", "Doctor Dolittle (1967 film)"): "The shipwreck and Great Pink Sea Snail scenes were filmed in the bay.",
    ("Monuriki", "Cast Away"): "The uninhabited island plays the film's anonymous desert island.",
    ("Nanuya Levu", "The Blue Lagoon (1980 film)"): "Principal photography took place on this private island.",
    ("Rocky Steps", "Rocky"): "Rocky runs up the 72 steps of the Philadelphia Museum of Art in training.",
    ("Café des 2 Moulins", "Amélie"): "The Montmartre cafe where Amélie works as a waitress.",
    ("Joker Stairs", "Joker (2019 film)"): "Arthur Fleck climbs the stairs daily - and dances down them in his Joker attire.",
}
